language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools-25.2.5
    - tools-25.2.5
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

script: ./gradlew lintBlurredEpisode8Debug