language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools # Yes this needs to be there twice, see https://github.com/travis-ci/travis-ci/issues/6040
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

script: ./gradlew lintBlurredEpisode8Debug